
// Optimized database connection for neon
// Generated by OtterSport Database Optimizer

import { drizzle } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error("DATABASE_URL environment variable is required");
}

// Optimized connection configuration
const sql = neon(connectionString, {
  poolSize: 5,
  maxConnections: 20,
  idleTimeout: 30000,
  connectionTimeout: 5000
});

export const db = drizzle(sql, { 
  schema,
  logger: process.env.NODE_ENV === 'development'
});

// Connection health monitoring
export const checkConnectionHealth = async () => {
  try {
    await db.select().from(exercises).limit(1);
    return { healthy: true, timestamp: new Date() };
  } catch (error) {
    return { healthy: false, error: error.message, timestamp: new Date() };
  }
};
